### ISSUE TITLE
docker support?

### ISSUE THREAD

**Issue by somedevreally** [mikefrancis/nosh#100]
hello,

great project, can this be self hosted? docker supported?

thanks

**Comment by mikefrancis** [comment]
Hi there @somedevreally,

You're free to fork or clone this repo on a server and [deploy to a myriad of destinations](https://nextjs.org/docs/deployment). There's no requirement to use a docker image for this but happy to accept a PR if you wanted to Dockerise this.

Is there a specific reason you want to self host this? [nosh.rocks](https://nosh.rocks) is free to use, highly available and all feed data is stored within your own client/browser, not on our servers (the only server-side aspect is used to fetch and transform the feed data).
