### ISSUE TITLE
Weird line shows up on the sidebar in dark theme

### ISSUE THREAD

**Issue by spiralw** [mikefrancis/nosh#113]
When I switch to dark theme, a dark line shows up on the sidebar.

Screenshots:

![light mode](https://user-images.githubusercontent.com/64013111/152606336-5527058e-005e-40cc-b353-438ea9fbc6e5.png)

![dark mode](https://user-images.githubusercontent.com/64013111/152606370-f8a19c94-2765-4da0-ba5a-486fc5ec3d34.png)

**Comment by mikefrancis** [comment]
Which browser/OS is this?

**Comment by spiralw** [comment]
just Chrome on Linux

**Comment by mikefrancis** [comment]
@spiralw I'm not a Linux user and cannot emulate this on BrowserStack so this would be something you'd need to debug and fix yourself.

**Comment by spiralw** [comment]
ok, no problem! I'll send a PR if I figure it out
