### ISSUE TITLE
Is this feature possible

### ISSUE THREAD

**Issue by felix2049lou** [mikefrancis/nosh#115]
[video](https://vimeo.com/675395911)
hi, I am asking about some of the features in the surface duo again. Is it possible that make the column size is changeable? I make this screenrecord by rss reader —NewsBlur.

**Comment by mikefrancis** [comment]
Hi, I think this would be possible yes. 

This project isn't in active development so this would need to be something you take on yourself.

**Comment by felix2049lou** [comment]
That's cool!
Sent from Surface Duo
________________________________
