### ISSUE TITLE
Post content hidden if post title contains "hidden" 

### ISSUE THREAD

**Issue by darekkay** [mikefrancis/nosh#38]
**Steps to reproduce**

- Add my blog feed: https://darekkay.com/atom.xml
- Open "focusing partially hidden elements in CSS" post

![image](https://user-images.githubusercontent.com/3101914/109008431-9bc91b00-76ad-11eb-96c9-f62135c04744.png)

The issue is that the title is being added as a CSS class. So when the title contains "hidden", a `hidden` class is applied, hiding the content.

**Comment by mikefrancis** [comment]
@darekkay Thanks for this. 

Had no idea why this was being done to be honest, cannot remember the rationale behind that one!
