### ISSUE TITLE
Put number of subscribers in the HTTP request

### ISSUE THREAD

**Issue by darekkay** [mikefrancis/nosh#39]
Inoreader, Feedbin and Feedly put the number of subscribers into their HTTP request (as "user agent"):

```
"GET /atom.xml" 304 0 "Mozilla/5.0 (compatible; inoreader.com; 9 subscribers)"
"GET /atom.xml" 304 0 "Feedbin feed-id:1524967 - 5 subscribers"
"GET /atom.xml" 304 0 "Feedly/1.0 (+http://www.feedly.com/fetcher.html; 16 subscribers; like FeedFetcher-Google)"
```

Right now, I'm getting this from nosh:

```
"GET /atom.xml" 304 0 "-" "axios/0.21.1"
```

It's rather very low prio, but something I really like from publisher perspective to [estimate my subscriber count](https://darekkay.com/blog/rss-subscriber-count/).

**Comment by mikefrancis** [comment]
@darekkay I'm not sure how we'd do this as a user's subscriptions are all stored client-side. 

Open to any ideas if you have any.

**Comment by mikefrancis** [comment]
I can add `nosh/version` as the `User-Agent` for the main request to the subscription which would at least allow you to aggregate this from logs?

**Comment by darekkay** [comment]
> I'm not sure how we'd do this as a user's subscriptions are all stored client-side.

The request still goes through nosh, right (POST `/get-feed`)? But I agree that it's rather inaccurate and not worth the effort. I will close this request.

> I can add `nosh/version` as the `User-Agent` for the main request to the subscription which would at least allow you to aggregate this from logs?

Yes, using `nosh` instead of `axios` is a great idea, as it has two advantages:

1. Non-invasive advertisement - when analysing access logs, people will notice nosh as an RSS client.
2. Some tools, like [goaccess](https://goaccess.io/), group the requests by browser, with a special group for RSS clients.
