### ISSUE TITLE
The little problem  in Microsoft surface duo  

### ISSUE THREAD

**Issue by felix2049lou** [mikefrancis/nosh#99]
Hi, developer. I am a new user of your application. I love to use this application in surface duo and I wish that the application could suitable layout in Microsoft surface duo. Microsoft has a CSS and JavaScript update for web developers. Whether the application be recoded for Microsoft surface duo might be difficult?

https://devblogs.microsoft.com/surface-duo/foldable-css-javascript-edge-96/

**Comment by mikefrancis** [comment]
Hi there @felix2049lou

I'm afraid I don't have the hardware or bandwidth to do this, would happily accept a Pull Request though if this is something you'd like to contribute.
